### ISSUE TITLE
App crashes for specific game (maybe related to games forked from demo boards)

### ISSUE THREAD

**Issue by bjeanes** [honganhkhoa/Surround#1]
For me and a friend. Started at the same time and no recent updates, so I'm _assumign_ that OGS broke their API in some way. Anything I can do to help your reproduce or to otherwise help fix it? I love this app and it makes such a difference to have a native app for OGS. Thanks again for the app!

**Comment by Bart-Jan** [comment]
I just played a game. So not a general problem.
iPhone 10r, iOS 14.7.1

Ciao,


Bart-Jan Schuman.
_______________________________
With my iPhone from Pliening.

**Comment by Bart-Jan** [comment]
Game play, chat, all fine.

Can you supply us with an error message or a stack crawl of the crashes.

Ciao,


Bart-Jan Schuman.
_______________________________
With my iPhone from the A9.

**Comment by bjeanes** [comment]
How do I get the error message? Does the app leave a log somewhere? (it's installed from App Store not compiled)

**Comment by bjeanes** [comment]
Huh OK so I think I figured out what this was. It is no longer crashing after completing the game I was playing with my other friend I mentioned.

So it seems to be something about that game in particular. The game was forked from a demo board, so I wonder if the API payload for that game doesn't meet the schema expected?

It was a private game ~~, but if you tell me your OGS username I can invite you as a viewer which may let you test this theory~~ (never mind, I can't see how to add people to as a viewer to a game, just to a review).

**Comment by bjeanes** [comment]
It seems private games can still be accessed from API without auth, though. https://online-go.com/api/v1/games/36141538 is the game JSON. I can see that the `initial_state` key has a very different value for instance.

**Comment by honganhkhoa** [comment]
@bjeanes Can you try adding me to the game using the "Access settings" option at the top? My OGS username is [HongAnhKhoa](https://online-go.com/player/314459/)

<img width="244" alt="Screen Shot 2021-10-08 at 11 00 51" src="https://user-images.githubusercontent.com/1177495/136496356-f3b1ef0a-7f59-4df0-a8c9-4b3cf80699af.png">

I have tried creating private games and games forked from demo boards, but couldn't reproduce the crash yet.

**Comment by bjeanes** [comment]
@honganhkhoa I would of course, but it seems that menu disappears or moves after the game concludes
![image](https://user-images.githubusercontent.com/2560/136498509-7ef41c9d-6a50-49e1-8e9f-5063d4e8e2a0.png)

**Comment by bjeanes** [comment]
I forked the game as a challenge to you. Perhaps it will exhibit the same issue

**Comment by honganhkhoa** [comment]
It does not crash for me, but I think I know the issue now: earlier versions of the app would crash if a shared variation in chat contains a pass. I added a workaround for it in commit 020ef02f119329054b5c4d03fdb7611476e21b4a so it should not crash anymore. I still need to implement proper support for those chats though.

Is it working properly from your side?

**Comment by bjeanes** [comment]
The app stopped crashing after the game was concluded, so it's hard to tell. The game I forked today for you does not crash though.

I say we close this issue and if it comes up again there will at least be some clues here.

**Comment by honganhkhoa** [comment]
Yeah, thank you very much for your help.

**Comment by kevincoleman** [comment]
I can chime in to say this exactly thing happened to me when I had a game forked from a demo board. Once it was completed the issue went away.
