### ISSUE TITLE
Getting logged out several times a day

### ISSUE THREAD

**Issue by bjeanes** [honganhkhoa/Surround#10]
It seems the app won't stay logged in for more than a few hours per day and I keep missing moves as a result. 

Any ideas how to resolve this?

**Comment by honganhkhoa** [comment]
@bjeanes Could you share your iOS version and the type of account you are using for logging in (OGS/Google/Facebook/etc.)?

Also, has this issue just started recently?

**Comment by bjeanes** [comment]
It's an OGS account without any social login. It's been happening for about 3 weeks. iOS 17.2.1 on an iPhone 15 Pro.

**Comment by honganhkhoa** [comment]
@bjeanes Can you help to reinstall the app and keep push notifications disabled to see if it helps with the issue. I haven't figured out all the details yet but it looks like this bug was caused by some interaction between the app and the notification server.

**Comment by bjeanes** [comment]
I have reinstalled the app several times already. How do I keep push notifications disabled? I am not taking any explicit step to re-enable them after re-installation AFAICT. I actually use the Widget on the home screen more than anything to see when there is a move to be made.

Anecdotally on this bug (which I continue to experience) is that it will stay logged in for quite a while but then as soon as I go into app and make several moves and then close app, the widget will show me as logged out. The moves I made all go through, but the session invalidation seems to happen after I take moves (or perhaps when the server reports no moves to be made i.e. I clear all the games). Hopefully that's helpful...

**Comment by bjeanes** [comment]
![image](https://github.com/honganhkhoa/Surround/assets/2560/4aa2604f-11b8-44f6-af20-6d51088291f6)

So actually notifications are off. I'll have to wait and see to be sure my memory is serving correctly but I feel that I have been getting notifications nonetheless. Perhaps this is due to this other issue I raised though: https://github.com/honganhkhoa/Surround/issues/6

**Comment by honganhkhoa** [comment]
@bjeanes Thanks a lot for the information. Could you help to try the TestFlight version below to see if it helps with this issue (and also #6)?

https://testflight.apple.com/join/2JHF5Zut

**Comment by bjeanes** [comment]
OK I've installed it note and I'll let you know what I experience. If it is ongoing, perhaps we can find a way for be to capture some debug data out request logs

**Comment by bjeanes** [comment]
It didn't long me out for a few days but now it's after almost every move. I really wonder if it's a specific game or game state. Any thoughts on adding some logging for me to share with you?

**Comment by honganhkhoa** [comment]
@bjeanes Thanks for the update. I have updated another TestFlight version (2024022701) with a potential fix (ed7423f). Could you help to try that out?

I am not used to collecting logs on device so I will have to learn how to do that first, or probably I can give you a special build that logs to my server...

**Comment by bjeanes** [comment]
So far this seems better. I haven't yet ben logged out. I wonder what response status I was getting if not 403 and why that might be...

**Comment by honganhkhoa** [comment]
I guess it's not an HTTP error but some kind of client exception, maybe it happens when you lock your phone while the app is active, or some kind of network changes.

I have not been able to reproduce it though, so that is just my guess. The change should be good anyway as it also prevents a logout in case the server returns HTTP 5xx.

**Comment by bjeanes** [comment]
It definitely seemed like it happened immediately after I made certain moves on certain games. Maybe it's a weird game state thing causing either the server to error or the client to fail to handle the response?

Either way, it hasn't reoccured since your change, so 🎉
