### ISSUE TITLE
iOS 15 support?

### ISSUE THREAD

**Issue by raphnet** [honganhkhoa/Surround#13]
I see the target was changed to iOS 16 a few months ago... I was wondering if keeping support for iOS15 (actually 15.7 or later) would somehow be possible? 

I have an older phone I would like to let someone use to play on OGS...

**Comment by honganhkhoa** [comment]
It's not impossible but I will need to disable a few minor features for that. However, since I will have to eventually drop iOS 15 support some day, I would prefer to drop it now because 1.3.11 has been the most stable version for a while. You should still be able to download 1.3.11 to an iOS 15 device.

Is your older phone an iPhone SE?

**Comment by raphnet** [comment]
The older phone is an iPhone 7.

I already have the latest compatible version of Surround installed, but the person who would be using it only understands Japanese, so ideally I would have liked to run a version of Surround that has the translation...

**Comment by honganhkhoa** [comment]
I see. Let me check on how easy/hard it is to support iOS 15 for one more version.

**Comment by honganhkhoa** [comment]
Hi @raphnet,

I have updated a TestFlight build with iOS 15 support (15.5 and later) to the TestFlight link I sent you before. Can you check it out to see if it works?

**Comment by raphnet** [comment]
Wonderful, we installed the app yesterday, so far it seem to be working fine!

**Comment by raphnet** [comment]
Based on what you had to do to support IOS15, is there a particular area of the app we should pay attention to?

**Comment by honganhkhoa** [comment]
The biggest difference is in the navigation structures (iOS 16 uses the new `NavigationStack` and `NavigationSplitView`), so if you can navigate everywhere in the app without issues then it should be fine.

**Comment by honganhkhoa** [comment]
iOS 15 support has been released in version 1.3.14, so I'm closing this issue.
