### ISSUE TITLE
I have several games which are not showing up

### ISSUE THREAD

**Issue by bjeanes** [honganhkhoa/Surround#3]
I've had two games (both with same player) that exhibited this behaviour:

https://online-go.com/game/42829652
https://online-go.com/game/43026687

The games are both private, but I have added https://online-go.com/player/314459/HongAnhKhoa (which I hope is you).

In both cases, the other player sent the challenge. Surround showed the challenges and allowed me to accept and for me to play moves. As far as I can tell, once it reached SD the same thing happened to both: it showed that it was my turn, but it didn't show my opponent's last move and instead I could place a stone of their colour. Restarting the app made the game disappear from the list and never return.

<details><summary>screenshots</summary>
<img width="797" alt="Screen Shot 2022-04-29 at 7 47 04 am" src="https://user-images.githubusercontent.com/2560/165852053-f448d66f-d1dc-410a-807a-ff4071242d05.png">

![IMG_B2675332AC91-1](https://user-images.githubusercontent.com/2560/165852224-b9e72ac6-7068-49fa-a0f6-012397d68be2.jpeg)
</details>

Let me know if there are any details I can provide to debug this issue, such as JSON payloads from my account (if they are different to what you can see once I gave you access).

**Comment by bjeanes** [comment]
As of a few moments ago, it seems to be happening in multiple games, many of which are not private nor in sudden death:

<img width="1442" alt="Screen Shot 2022-04-30 at 5 45 20 pm" src="https://user-images.githubusercontent.com/2560/166096891-19c86552-71bf-427f-a85b-ad7ca80ad25c.png">

![IMG_2200](https://user-images.githubusercontent.com/2560/166096888-f077f63c-2e0f-47b0-acdd-442bc9d24a2f.PNG)

The two other games which are now hidden are:

https://online-go.com/game/42620151
https://online-go.com/game/43290222

**Comment by honganhkhoa** [comment]
Hi @bjeanes,

Thank you very much for reporting this. I have just released version 1.3.4 with the fix for this. Could you update and try again to see if it works?

**Comment by bjeanes** [comment]
Yes! They show up now. Thank you 🙏 

~~what was the issue?~~ never mind I saw the commit. I'm guessing they changed the API subtly for this to arise, right?
