### ISSUE TITLE
Resigned/timed games not clearing; widget frozen

### ISSUE THREAD

**Issue by bjeanes** [honganhkhoa/Surround#4]
I have 2 resigned games (lost) and one timed out game (won) which are stuck in the "waiting for opponents/teammates" section. My OGS account: https://online-go.com/player/936790/. All the games in question are public:

https://online-go.com/game/45546917
https://online-go.com/game/45546910
https://online-go.com/game/45449370

![IMG_A00A10E1DDBF-1](https://user-images.githubusercontent.com/2560/183220677-1190e82e-b7e5-4f90-a9c9-554ceb1bd5c3.jpeg)

In fact, I am getting "you have 3 hours left to make a move" push notifications on the resigned game with `renlo`.

The widget has also been frozen with a state from last week and no longer updates.

![IMG_04ADE785FF1F-1](https://user-images.githubusercontent.com/2560/183220868-69fad42c-64d8-4055-a64f-2aa7c287b1ab.jpeg)

**Comment by bjeanes** [comment]
I opened the app on macOS for first time in a while and it seems to be caching even more finished games:

<img width="1210" alt="Screen Shot 2022-08-06 at 8 50 14 am" src="https://user-images.githubusercontent.com/2560/183220967-dcef77ff-f735-4e55-92a4-3e037390cc0a.png">

The Mac widget also is stale:

<img width="358" alt="Screen Shot 2022-08-06 at 8 52 03 am" src="https://user-images.githubusercontent.com/2560/183221117-5a4860bc-4ff8-473b-ba16-b1d51ca83597.png">

That top-right game is actually much further along:

<img width="485" alt="Screen Shot 2022-08-06 at 8 52 58 am" src="https://user-images.githubusercontent.com/2560/183221183-7a82c5c6-526c-4aa6-9a16-69fa812cc2ef.png">

**Comment by honganhkhoa** [comment]
Hi, thank you very much for the report.

It looks like your account is in a "half logged out" state, which makes some APIs fail (but the other APIs continue to work).

Can you try logging out of the your OGS account then log in again?

**Comment by bjeanes** [comment]
Oh wow great catch! That totally worked, thanks.

I would never have anticipated that as the explanation. I did consider trying this but because it was happening on two devices, it didn't seem like it was session-related.
