### ISSUE TITLE
Push notifications doubling up; second one delayed

### ISSUE THREAD

**Issue by bjeanes** [honganhkhoa/Surround#6]
I can't remember when this started, but possibly months ago.

I'm having an issue where each notifiable event is creating 2 notifications. Most annoying, however, is that the second one often comes a few minutes after the first. This usually means that I've already responded to the notification (by making a move) and then the second notification brings me back to the game where there are no moves to be made.

Is there a way to reset and re-register the notifications? My OGS username is same as GH, if important.

**Comment by honganhkhoa** [comment]
Hi @bjeanes,

Sorry for the late reply.

Is the issue still happening for you? Are you using the home screen widget?

Logging out on all devices then logging back in should reset the notifications, but I am not sure if it would help. I will check further to see if I can find any possible cause...

**Comment by bjeanes** [comment]
Yep still happening for me. I am using the home screen widget, yep. I believe I only have it on a single device

**Comment by honganhkhoa** [comment]
Hi @bjeanes,

Does this issue still happen to you with the recent app versions (either 1.3.12 or 1.3.13)?

**Comment by bjeanes** [comment]
I turned notifications off due to the issue so haven't been able to tell. I'll re-enable them and let you know.

**Comment by bjeanes** [comment]
I don't seem to be getting double notifications currently. I'll close this for now and reopen if I experience it again.
